Legrandin master
Legrandin/pycryptodome pull request #552
Opened 2021-09-28 12:44 UTC by arnimarj

2021-09-28 16:36 UTC, Varbin requested changes

2021-09-28 16:36 UTC, Varbin commented on lib/Crypto/Cipher/PKCS1_v1_5.pyi
> +                expected_pt_len: Optional[int] = ...) -> Union[bytes, T]: ...
Shouldn't line 16 be `sentinel: T`?

2021-09-28 16:36 UTC, Varbin commented on lib/Crypto/Cipher/PKCS1_v1_5.pyi
> -    def can_decrypt(self) -> bool: ...
What happened to `can_decrypt`?

2021-09-28 17:17 UTC, arnimarj commented on lib/Crypto/Cipher/PKCS1_v1_5.pyi
> -    def can_decrypt(self) -> bool: ...
Sorry... a botched merge from my fork

2021-09-28 17:17 UTC, arnimarj commented on lib/Crypto/Cipher/PKCS1_v1_5.pyi
> +                expected_pt_len: Optional[int] = ...) -> Union[bytes, T]: ...
Correct. Fixed.

2021-10-01 21:13 UTC, Legrandin commented
Merged, thanks!

2021-10-01 21:13 UTC, closed without merging